spring.application.name=cabbook
# server.servlet.context-path=/cabbook
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.port=8081
springfox.documentation.swagger.v2.path=/v2/api-docs
springfox.documentation.swagger-ui.base-url=http://localhost:8080

# springdoc.swagger-ui.path=/cabbook/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=*


