spring.config.name=local

# PostgreSQL JDBC Configuration
spring.datasource.url=jdbc:postgresql://172.17.0.2:5432/db
spring.datasource.username=rishav
spring.datasource.password=rishav
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration (if you're using Spring Data JPA)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect    <removed because logs told to do that>
# log arguement was :- HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' 
#(remove the property setting and it will be selected by default)

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    

# very important for open API config
springdoc.api-docs.enabled=true
springdoc.show-actuator=false
springdoc.packages-to-scan=com.jeriv.springboot.controller
